# Site settings
title: George Racu
email: me@georgeracu.com
description: "George Racu's personal page."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://georgeracu.github.io" # the base hostname & protocol for your site
twitter_username: georgeracu
github_username: georgeracu
google_analytics: UA-53216185-7

theme: alembic-jekyll-theme

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
